//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezpos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_ID { get; set; }
        public string Customer_Firstname { get; set; }
        public string Customer_Lastname { get; set; }
        public string Customer_Cell { get; set; }
        public string Customer_Home { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_State { get; set; }
        public string Customer_Zip { get; set; }
    }
}
