//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ezpos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Product_name { get; set; }
        public string Product_Description { get; set; }
        public Nullable<decimal> Product_Wholesaler_Cost { get; set; }
        public Nullable<decimal> Product_Min_Price { get; set; }
        public Nullable<decimal> Product_Max_Price { get; set; }
        public Nullable<int> Product_Quantity { get; set; }
    }
}
